openapi: 3.0.1
info:
  title: testing source file
  description: application info
  version: 1.0.0
servers:
  - url: http://localhost:8081/api
    variables:
      /applications/get/requestBody/schemas:
        default: '#/components/schemas/ApplicationVo'
      /applications/post/requestBody/schemas:
        default: '#/components/schemas/ApplicationVo'
paths:
  /applications:
    get:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationVo'
        required: false
      responses:
        200:
          description: success!
components:
  schemas:
    Application:
      required:
        - id
      type: object
      properties:
        appName:
          type: string
          example: test
        appProfile:
          type: string
          example: test
        appLabel:
          type: string
          example: test
        appCreated:
          type: date
          example: 2022-06-10
        appModified:
          type: date
          example: 2022-06-11
    ApplicationVo:
      allOf: # Combines the main `Application` schema with `ApplicationVo`-specific properties
        - $ref: '#/components/schemas/Application'
        - type: object
          # all other properties specific to a `Dog`
        - required:
            - appName